name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - uses: codecov/codecov-action@v2      

     # - name: Prepare database for integration tests
      #  run: | 
       #   sudo /etc/init.d/mysql start
        #  mysql -uroot -proot < pruebas.db
         # mvn --batch-mode --update-snapshots compile 
         # mvn --batch-mode --update-snapshots datanucleus:enhance
         # mvn --batch-mode --update-snapshots datanucleus:schema-create
         # mvn --batch-mode --update-snapshots exec:java -Pdatos
         
      - name: Set up MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
      - run: mysql --user 'root' --host '127.0.0.1' -e 'CREATE DATABASE bd_bspq;'

      - name: Retrieve version
        run: echo "::set-output name=TAG_NAME::$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)"
        id: version

      - uses: dev-drprasad/delete-tag-and-release@v0.1.3
        with:
          delete_release: true
          tag_name: ${{ steps.version.outputs.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
